name: Compile Minecraft Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 25 Runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '25'

      - name: Setup Gradle 9.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.4'

      - name: Compile Mod
        run: gradle build

      - name: Upload Finished Jar
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Mod-Jar
          path: build/libs/*.jar
